# Configuration eth1 / Ansible playbook
# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:

# Configurations Réseaux
  - name: Suppression de la passerelle par défaut
    shell: ip route del default1
    ignore_errors: true

  - name: Configuration de VM3/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.163/28 


  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"



  - name: Configuration de VM3/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip6: fc00:1234:4::3/64

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth2 via ansible"



  - name: Configuration de la route vers LAN1 via VM2
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4: 172.16.2.128/28 172.16.2.162
      state: present

  - name: Configuration de la route vers LAN2 via VM2
    community.general.nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      routes6: fc00:1234:1::/64 fc00:1234:2::26
      state: present
